<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Tom Mault</title>
  <link rel="shortcut icon" href="/assets/images/favicon.ico">
  <link rel="stylesheet" href="/assets/css/style.css">
  <link rel="alternate" type="application/rss+xml" title="My Blog" href="/rss.xml">
  <link rel="stylesheet" href="/assets/css/highlight.css">
</head>
<body>

  <nav class="main-nav">
    
        <a href="/"> Home </a>
    

        <a href="https://twitter.com/tmault">Twitter</a>
    
    
        
            <a href="/about">About </a>
        
    

    <a class="cta" href="/feed.xml">Subscribe</a>
</nav>
  <div class="profile">
    <section id="wrapper">
        <header id="header">
        
            <a href="/">
                <img id="avatar" class="2x" src="/assets/images/avatar.png"/>
            </a>
        
            <h1>Tom Mault</h1>
            <h2>Graduate Consultant</h2>
        </header>
    </section>
</div>


  <section id="wrapper" class="">
    ---
name: Tom Mault
description: Graduate Consultant
meta_description: Graduate Consultant at Atos. Currently studying the Intro to Programming
  Nanodegree on Udacity.
aboutPage: true
markdown: kramdown
highlighter: pygments
gems:
- jekyll-paginate
paginate: 100
baseurl: "/"
domain_name: http://tmault.co.uk
google_analytics: UA-XXXXXXXX-X
disqus: true
disqus_shortname: tmault
url: http://tmault.co.uk
author: Tom Mault
authorTwitter: tmault
permalink: "/:year/:title/"
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: drafts
  values:
    layout: post
timezone: 

  </section>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="/assets/js/main.js"></script>
  <script src="/assets/js/highlight.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-XXXXXXXX-X', 'auto');
    ga('send', 'pageview');
  </script>
</body>
</html>



